#!/bin/bash

java -Xmx768M -XX:+UseCompressedOops -XX:MaxPermSize=384m \
        -Dhttp.proxyHost=devscreen.gudev.gnl -Dhttp.proxyPort=3128 \
        -Dsbt.boot.directory=$SBT_BOOT_DIR \
        $SBT_EXTRA_PARAMS \
        -jar `dirname $0`/dev/sbt-launch-0.11.0.jar "$@"

